- name: Validation Testing
  hosts: localhost
  connection: local
  roles:
    - initialization
    - seal
    - token
    - metrics
    - audit
  tags: backup

#- name: Check that a page returns a status 200 and fail if the word AWESOME is not in the page contents
#  uri:
#    url: http://www.example.com
#    return_content: yes
#  register: this
#  failed_when: "'AWESOME' not in this.content"