# tasks file for roles/audit
- name: Check that v1/sys/audit (GET) returns a status 200
  uri:
    url: "{{ vault.protocol }}://{{ vault.host }}/v1/sys/audit"
    method: GET
    headers:
        X-Vault-Token: "{{ vault.token_validator }}"

- name: Current Vault audit
  debug:
    msg: The current Audit Devices is -> {{(response.content|from_json)}} <-